# Imagen base: Ubuntu más reciente
FROM ubuntu:22.04

LABEL maintainer="Matias <matiaschop@hotmail.com>"
LABEL description="Contenedor Ubuntu para pruebas de HackFlow"

ENV DEBIAN_FRONTEND=noninteractive

# Actualiza el sistema e instala herramientas necesarias
RUN apt update && apt install -y \
    python3 \
    python3-pip \
    git \
    curl \
    nmap \
    netcat \
    nano \
    && apt clean

# Crear directorio de trabajo
WORKDIR /root/HackFlow

# Copia el contenido del proyecto al contenedor
COPY . /root/HackFlow

# Instala las dependencias Python del proyecto
RUN pip3 install --no-cache-dir -r requirements.txt

# Comando por defecto
CMD ["bash"]
